### PR TITLE
simplified translations

### PR DESCRIPTION
**Pull request by swurzinger**
Based on the work in #1321 this now targets v5 and changes the approach such that the language files are not generated during build time anymore, but dynamically on request and then cached.

As of now this PR implements the basic functionality and works, but some things are still missing.

- [x] improve translation extraction tool to detect translation strings more reliably
- [x] provide endpoint to generate combined lang file for core and modules
- [x] cache lang file
- [ ] clear cache when enabling/disabling a module
- [ ] cleanup/remove translation symlink functionality for modules
- [ ] provide artisan command to clear lang cache
- [ ] improve translation helper for modules
- [ ] restrict locales to configured known ones

### CODE REVIEW

**Comment by swurzinger** [comment]
I updated and integrated this into my fork https://github.com/swurzinger/NexoPOS/tree/stw/5-generic due to maintainer inactivity. Feel free to grab any fixes/improvements from there 😀

**Comment by swurzinger** [comment]
> Maintainer inactivity? Really ??? So a PR not qualified to be approved is because of the maintained inactivity?

There's no PR review, no hints what is good/bad about the changes, no reason for a rejection or any other response from the maintainer - since more than a year ago.

**Comment by Blair2004** [comment]
This was aligned to be similar to this [PR](https://github.com/Blair2004/NexoPOS/pull/1469) (also created by you) we've given a feedback on why we can't merge that [at the moment](https://github.com/Blair2004/NexoPOS/pull/1321#issuecomment-1436054431)

**Comment by swurzinger** [comment]
> This was aligned to be similar to this [PR](https://github.com/Blair2004/NexoPOS/pull/1469) (also created by you)

The mentioned PR is completely independent from the translations topic, that is addressed by this PR. The only thing in common is the lack of feedback / responses at a certain point for a long time 😞.

> we've given a feedback on why we can't merge that [at the moment](https://github.com/Blair2004/NexoPOS/pull/1321#issuecomment-1436054431)

This PR addresses the concern raised there. Instead of requiring to copy the translation files with composer (which would require to run composer after adding/removing modules) the translation file is dynymically built (and cached) at runtime. All translations from activated modules are integrated as well.

In my fork I implemented a variation the first approach: An artisan command builds the translation file and is triggered via composer + after enabling/disabling a module.

________

Any way, I stopped porting my changes back upstream for now, due to the reasons mentioned. Yet, feel free to approach me in case you want to follow up on any of the changes/ideas.

**Pull request closed without merging**
