### PR TITLE
hide registration button when registration disabled in settings

### PR DESCRIPTION
**Pull request by swurzinger**
show by default

### CODE REVIEW

**Comment by Blair2004** [comment]
Hey,
Thank you for your pull request . I'll review that 😉👍🏾

**Review by Blair2004 — APPROVED** [review]

**Comment by Blair2004** [comment]
By the way, upcoming pull request plus send those on either v4.8.x branch or v5.0.x branch.

**Comment by swurzinger** [comment]
> By the way, upcoming pull request plus send those on either v4.8.x branch or v5.0.x branch.

I'm not sure what you mean. Shall I re-target this PR to one of the mentioned branches? What's the current development branch and what's your versioning strategy?

**Comment by Blair2004** [comment]
> > By the way, upcoming pull request plus send those on either v4.8.x branch or v5.0.x branch.
> 
> 
> 
> I'm not sure if I understand what you mean? Shall I re-base this PR to one of the mentioned branches? What's the current development branch and what's your versioning strategy?

Currently the v4.8.x is the current branch. Most PR should be based on that. The Master branch is the stable branch every release are based on that (unless it's a security fix on previous branch like v4.7.x etc). The v5.0.x is the upcoming main branch, PR can also be based on that.

We need to double check PR, before merging to master. So we don't send PR to Master.

Thank you for your contribution anyway. You can keep it in mind for future 😊

**Comment by swurzinger** [comment]
Thanks, that branching strategy you're using is a bit unusual, but I understand it now.

Rebased onto v4.8.0 and retargeted PR to that branch.

**Review by Blair2004 — APPROVED** [review]

**Pull request merged**
